filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: host.docker.internal:5601
  username: elastic
  password: changeme

# output.logstash:
#   # The Logstash hosts
#   hosts: ["host.docker.internal:5044"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: changeme
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"